config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all.order("updated_at DESC")
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    flash[:notice] = "タスク「#{@task.name}」を登録しました。"
    redirect_to tasks_url
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    flash[:notice] = "タスク「#{@task.name}」を更新しました。"
    redirect_to tasks_url
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "タスク「#{@task.name}」を削除しました。"
    redirect_to tasks_url
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskleaf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="app-title navbar navbar-expand-md navbar-light bg-light">
      <div class="navbar-brand" href="#">Taskleaf</div>
    </nav>
    <div class="container">
      <% if flash.notice.present? %>
        <div class="alert alert-success">
          <%= flash.notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task, local: true do |form| %>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control', id: 'task_name' %>
    <% @task.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, rows: 5, class: 'form-control', id: 'task_description' %>
    <% @task.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>

<div class="nav justify-content-end">
  <%= link_to "タスク一覧", tasks_path, class: "nav-link" %>
</div>

<%= render partial: "form", locals: { task: @task } %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<%= link_to "新規登録", new_task_path, class: "btn btn-primary" %>

<div class="mb-3">
  <table class="table table-hover">
    <thead class="thead-default">
      <tr>
        <th><%= Task.human_attribute_name(:name) %></th>
        <th><%= Task.human_attribute_name(:created_at) %></th>
        <th><%= Task.human_attribute_name(:updated_at) %></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.name, task_path(task.id) %></td>
          <td><%= task.created_at %></td>
          <td><%= task.updated_at %></td>
          <td>
            <%= link_to "編集", edit_task_path(task.id), class: "btn btn-primary" %>
            <%= link_to "削除", task_path(task.id), method: :delete, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか？" }, class: "btn btn-primary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html.erb
<h1>タスク新規登録</h1>

<div class="nav justify-content-end">
  <%= link_to "タスク一覧", tasks_path, class: "nav-link" %>
</div>

<%= render partial: "form", locals: { task: @task } %>

app/views/tasks/show.html.erb
<h1>タスクの詳細</h1>
<div class="nav justify-content-end">
  <%= link_to "タスク一覧", tasks_path, class: "nav-link" %>
</div>

<table class="table table-hover">
  <tbody>
    <tr>
      <th><%= Task.human_attribute_name(:id) %></th>
      <td><%= @task.id %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:name) %></th>
      <td><%= @task.name %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:description) %></th>
      <td><%= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div") %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:created_at) %></th>
      <td><%= @task.created_at %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:updated_at) %></th>
      <td><%= @task.updated_at %></td>
    </tr>
  </tbody>
</table>

<%= link_to "編集", edit_task_path(@task.id), class: "btn btn-primary" %>
<%= link_to "削除", task_path(@task), method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか？" }, class: "btn btn-primary" %>